name: JMeter Performance Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Apache JMeter
        run: |
          wget -q https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.1.tgz
          tar -xzf apache-jmeter-5.4.1.tgz
          mv apache-jmeter-5.4.1 $HOME/apache-jmeter
          rm apache-jmeter-5.4.1.tgz
          chmod +x $HOME/apache-jmeter/bin/jmeter

      - name: Set up environment variables
        run: |
          echo "csvfile=$GITHUB_WORKSPACE/Product_1.csv" >> $GITHUB_ENV

      - name: Run JMeter Test with CSV file
        run: |
          mkdir -p reports/html
          $HOME/apache-jmeter/bin/jmeter -n -t PetStore_.jmx -l result.jtl -Jcsvfile=${csvfile}
          $HOME/apache-jmeter/bin/jmeter -g result.jtl -o ./reports/html/

      - name: Upload JMeter Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: result.jtl

      - name: Upload HTML Reports
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-html-reports
          path: reports/html
